### ISSUE TITLE
No calendar events shown

### ISSUE THREAD

**Issue by achimmm** [bramwaas/joomla_mod_simple_ical_block#13] opened 2023-04-15 12:05 UTC
Hi,
I used the module on a J4 site and it worked very well. Some days ago (cannot state exactly when), no event data is shown anymore. Can you give me a hint on where to look for logs?

**Comment by bramwaas** [comment] 2023-04-15 14:23
Hi,

You can try the cache file in <your home directory>/administrator/cache/SimpleicalBlock/
But I think if ho dat is shown this will also be empty.

If you cannot reach the ical file you may find a line like this if you inspect (with chrome or firefox) the website where the module should display:

https://www.google.com/calendar/ical/example/public/basic.ics is the name of the calendar you try to reach (in this case I try to reache example that does not exist of course.
If you give this url in the address field of your browser it should display/download an ical file but you may have an error here.

There are no other special log's for this module. 
Maybe you can put in
System / Global configuration /TAB  Server / Error reporting  at Maximum
Depending on your configuration you can see the error in a log file or maybe in the screen.

**Comment by achimmm** [comment] 2023-04-15 17:22
Hi and thanks for your reply.

What I found out:

  *   the cache files are empty
  *   the configured URL works (in the browser and in a ssh-session on the server with curl): https://xttv.oettv.info/public/ics_termine.php?tabkzg=URFA1&dauer=180
  *   the joomla logs contains no error with todays date (although set to "max")
  *   the deprecated log contains this errors (and some others)

2023-04-15T17:20:04+00:00     WARNING 86.56.241.197   deprecated  Joomla\CMS\Factory::getCache() is deprecated. The cache controller should be fetched from the factory. - [ROOT]/libraries/src/Factory.php - Line 370
2023-04-15T17:20:04+00:00     WARNING 86.56.241.197   deprecated  Since joomla/event 2.0.0: Not passing an event object to Joomla\Event\Dispatcher::dispatch() is deprecated, as of 3.0 the $event argument will be required. - [ROOT]/libraries/vendor/symfony/deprecation-contracts/function.php - Line 25
2023-04-15T17:20:04+00:00     WARNING 86.56.241.197   deprecated  Since joomla/event 2.0.0: Not passing an event object to Joomla\Event\Dispatcher::dispatch() is deprecated, as of 3.0 the $event argument will be required. - [ROOT]/libraries/vendor/symfony/deprecation-contracts/function.php - Line 25
2023-04-15T17:20:04+00:00     WARNING 86.56.241.197   deprecated  Joomla\CMS\Factory::getDocument() is deprecated. Load the document from the dependency injection container or via Joomla\CMS\Factory::getApplication()->getDocument(). - [ROOT]/libraries/src/Factory.php - Line 300

________________________________
Von: Bram Waasdorp ***@***.***>
Gesendet: Samstag, 15. April 2023 16:23
An: bramwaas/joomla_mod_simple_ical_block ***@***.***>
Cc: Achim Mühlberger ***@***.***>; Author ***@***.***>
Betreff: Re: [bramwaas/joomla_mod_simple_ical_block] No calendar events shown (Issue #13)


Hi,

You can try the cache file in /administrator/cache/SimpleicalBlock/
But I think if ho dat is shown this will also be empty.

If you cannot reach the ical file you may find a line like this if you inspect (with chrome or firefox) the website where the module should display:

https://www.google.com/calendar/ical/example/public/basic.ics is the name of the calendar you try to reach (in this case I try to reache example that does not exist of course.
If you give this url in the address field of your browser it should display/download an ical file but you may have an error here.

There are no other special log's for this module.
Maybe you can put in
System / Global configuration /TAB Server / Error reporting at Maximum
Depending on your configuration you can see the error in a log file or maybe in the screen.

**Comment by achimmm** [comment] 2023-04-15 17:56
Hi,

tried it on a clean joomla 4.2.9 installation (Windows server) - result is the same. The cache file is empty, no data is displayed).
________________________________
Von: Achim Mühlberger ***@***.***>
Gesendet: Samstag, 15. April 2023 19:22
An: bramwaas/joomla_mod_simple_ical_block ***@***.***>
Betreff: AW: [bramwaas/joomla_mod_simple_ical_block] No calendar events shown (Issue #13)

Hi and thanks for your reply.

What I found out:

  *   the cache files are empty
  *   the configured URL works (in the browser and in a ssh-session on the server with curl): https://xttv.oettv.info/public/ics_termine.php?tabkzg=URFA1&dauer=180
  *   the joomla logs contains no error with todays date (although set to "max")
  *   the deprecated log contains this errors (and some others)

2023-04-15T17:20:04+00:00     WARNING 86.56.241.197   deprecated  Joomla\CMS\Factory::getCache() is deprecated. The cache controller should be fetched from the factory. - [ROOT]/libraries/src/Factory.php - Line 370
2023-04-15T17:20:04+00:00     WARNING 86.56.241.197   deprecated  Since joomla/event 2.0.0: Not passing an event object to Joomla\Event\Dispatcher::dispatch() is deprecated, as of 3.0 the $event argument will be required. - [ROOT]/libraries/vendor/symfony/deprecation-contracts/function.php - Line 25
2023-04-15T17:20:04+00:00     WARNING 86.56.241.197   deprecated  Since joomla/event 2.0.0: Not passing an event object to Joomla\Event\Dispatcher::dispatch() is deprecated, as of 3.0 the $event argument will be required. - [ROOT]/libraries/vendor/symfony/deprecation-contracts/function.php - Line 25
2023-04-15T17:20:04+00:00     WARNING 86.56.241.197   deprecated  Joomla\CMS\Factory::getDocument() is deprecated. Load the document from the dependency injection container or via Joomla\CMS\Factory::getApplication()->getDocument(). - [ROOT]/libraries/src/Factory.php - Line 300

________________________________
Von: Bram Waasdorp ***@***.***>
Gesendet: Samstag, 15. April 2023 16:23
An: bramwaas/joomla_mod_simple_ical_block ***@***.***>
Cc: Achim Mühlberger ***@***.***>; Author ***@***.***>
Betreff: Re: [bramwaas/joomla_mod_simple_ical_block] No calendar events shown (Issue #13)


Hi,

You can try the cache file in /administrator/cache/SimpleicalBlock/
But I think if ho dat is shown this will also be empty.

If you cannot reach the ical file you may find a line like this if you inspect (with chrome or firefox) the website where the module should display:

https://www.google.com/calendar/ical/example/public/basic.ics is the name of the calendar you try to reach (in this case I try to reache example that does not exist of course.
If you give this url in the address field of your browser it should display/download an ical file but you may have an error here.

There are no other special log's for this module.
Maybe you can put in
System / Global configuration /TAB Server / Error reporting at Maximum
Depending on your configuration you can see the error in a log file or maybe in the screen.

**Comment by bramwaas** [comment] 2023-04-15 18:58
Hi achimm,
thanks for your efforts.

Too bad it hasn't yielded any results yet.

The Deprecated warnings are just warnings, they won't really become errors until one of the next updates. So I don't think that's the source of the problem.

If you don't mind, I'll try to find the cause with your iCal file. Can and may I use
https://xttv.oettv.info/public/ics_termine.php?tabkzg=URFA1&dauer=180
as calendar id.

And what values for 'Number of events' and 'Future days' do you use?

Kind regards,

Bram Waasdorp

**Comment by achimmm** [comment] 2023-04-15 19:20
Of course.

#events is 30, Future days 92.

Maybe this file has no future events- i tested it with another one which has future events but the result was the same

Thx for your help!

Am 15.04.2023 um 20:58 schrieb Bram Waasdorp ***@***.***>:

﻿

Hi achimm,
thanks for your efforts.

Too bad it hasn't yielded any results yet.

The Deprecated warnings are just warnings, they won't really become errors until one of the next updates. So I don't think that's the source of the problem.

If you don't mind, I'll try to find the cause with your iCal file. Can and may I use
https://xttv.oettv.info/public/ics_termine.php?tabkzg=URFA1&dauer=180
as calendar id.

And what values for 'Number of events' and 'Future days' do you use?

Kind regards,

Bram Waasdorp

**Comment by bramwaas** [comment] 2023-04-15 21:49
Hi,

If the file has no future eventss the module will not display any data.
The selection is events (or occurencies of recurrent events) from (now) until (now + future days)
maximized by Number of events.

The latest event in te file   https://xttv.oe .... is the 28th of march.

So it is by design correct that no data is displayed.

For testing purpose I have set the starttime 30 days before now() and the the calender displayed two events:
 One on 22nd of march and one on 28th of march.

replaced line 297 of modules/mod_simple_ical_block/src/IcsParser.php:
`        $this->now = time();
`
by
`        $this->now = time() - (30*24*3600);
`

If you have a file with future events that are not displayed I can try to find the cause but with this file I couldn't find any problem.

Kind regards,

Bram Waasdorp

**Comment by achimmm** [comment] 2023-04-16 09:29
Thx a lot - I tried it with another ical file WITH future events - and it worked!

May I ask for a future feature - if there are no future events, a configurable text should be displayable.

Have a nice rest-weekend!

lg, Achim

________________________________
Von: Bram Waasdorp ***@***.***>
Gesendet: Samstag, 15. April 2023 23:49
An: bramwaas/joomla_mod_simple_ical_block ***@***.***>
Cc: Achim Mühlberger ***@***.***>; Author ***@***.***>
Betreff: Re: [bramwaas/joomla_mod_simple_ical_block] No calendar events shown (Issue #13)


Hi,

If the file has no future eventss the module will not display any data.
The selection is events (or occurencies of recurrent events) from (now) until (now + future days)
maximized by Number of events.

The latest event in te file https://xttv.oe .... is the 28th of march.

So it is by design correct that no data is displayed.

For testing purpose I have set the starttime 30 days before now() and the the calender displayed two events:
One on 22nd of march and one on 28th of march.

replaced line 297 of modules/mod_simple_ical_block/src/IcsParser.php:
$this->now = time();
by
$this->now = time() - (30*24*3600);

If you have a file with future events that are not displayed I can try to find the cause but with this file I couldn't find any problem.

Kind regards,

Bram Waasdorp

**Comment by bramwaas** [comment] 2023-04-16 10:57
Hi Achim,

I'm glad it's working for you now.
It was nice working with you.

I think your feature request is a good addition so I'll implement that.

For now, I'm closing this issue.

Have a nice weekend.
Regards

Bram Waasdorp.

**Closed** 2023-04-16 10:58 UTC
